name: Rebuild on push (CI)
on: push
jobs:
  build:
    name: Rebuild and commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Install deps
        run: yarn install
      - name: Build package
        run: yarn build
      - name: Check if rebuilding resulted in changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - name: Commit build files
        if: steps.changes.outputs.changed == 1
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add dist/
          git commit -m "ci(publish): *AUTO* rebuild source"
          git push origin main
